select country,
year,
Nb_beds_psy,
Nb_psychiatrist,
health_expenditure,
`chronic_disease_share_%` AS chronic_disease_share,
death_suicide_per_100000,
death_alcohol_per_100000,
nb_years_healthy_life,
alcohol_consumption,
antidepressants_consumption,
anxiolytics_consumption,
hypnotics_consumption,
`Performing health-enhancing physical activity _%` as sports_share,
`Overall perceived social support - Strong _%` as social_support_strong_share,
`Overall perceived social support -Intermediate_%` as social_support_intermediate_share,
`Overall perceived social support -Poor_%` as social_support_poor_share,
`Life evaluation_3-year AVG` as life_evaluation_3Y,
population,
round(Nb_beds_psy/population*100000,2) as beds_per_100000,
round(Nb_psychiatrist/population*100000,2) as psychiatrist_per_100000,
round(health_expenditure/population*100000,2) as health_exp_per_100000,
round(antidepressants_consumption+anxiolytics_consumption+hypnotics_consumption,2) as total_treatment_consumption
from {{ ref('int_merge_pop_health_europe') }}

