version: 2
sources:
   - name: raw
     schema: mental_health_raw_data #Path of the table in BQ
     description: mental health project raw data source
     tables:
         - name: mental_illnesses_prevalence
           identifier: mental_illnesses_prevalence #What is the exact name of the table in  BQ
           description: Most prevalent mental illnesses per country from 1990 to 2019
           columns:
             - name: entity
               description: country
               tests:
                 - not_null
             - name: code
               description: country code
             - name: year
               description: year
               tests:
                - not_null
             - name: schizophrenia_disorders
               description: schizophrenia
               tests:
                - not_null
             - name: depressive_disorders
               description: depression
               tests:
                - not_null
             - name: anxiety_disorders
               description: anxiety
               tests:
                - not_null
             - name: bipolar_disorders
               description: bipolarity
               tests:
                - not_null
             - name: eating_disorders
               description: eating disorders
               tests:
                - not_null
         - name: burden_disease
           identifier: burden_disease_from_each_mental_illness
           description: DALY = Disability-Adjusted Life Year
           columns:
             - name: entity
               description: country
               tests:
                 - not_null
             - name: code
               description: country code
             - name: year
               description: year
               tests:
                 - not_null
             - name: dalys_depressive_disorders
               description: Disability-Adjusted Life Year for depressive disorders (nb d'années de vie en bonne santé perdues, années de vie perdues à cause d'un décès prématuré ou années vécues avec une maladie ou un handicap)
               tests:
                 - not_null                 
             - name: dalys_schizophrenia
               description: Disability-Adjusted Life Year for schizophrenia (nb d'années de vie en bonne santé perdues, années de vie perdues à cause d'un décès prématuré ou années vécues avec une maladie ou un handicap)
               tests:
                 - not_null   
             - name: dalys_bipolar_disorder
               description: Disability-Adjusted Life Year for bipolar disorder (nb d'années de vie en bonne santé perdues, années de vie perdues à cause d'un décès prématuré ou années vécues avec une maladie ou un handicap)
               tests:
                 - not_null   
             - name: dalys_eating_disorders
               description: Disability-Adjusted Life Year for eating disorders (nb d'années de vie en bonne santé perdues, années de vie perdues à cause d'un décès prématuré ou années vécues avec une maladie ou un handicap)
               tests:
                 - not_null
             - name: dalys_anxiety_disorders
               description: Disability-Adjusted Life Year for anxiety disorders (nb d'années de vie en bonne santé perdues, années de vie perdues à cause d'un décès prématuré ou années vécues avec une maladie ou un handicap)
               tests:
                 - not_null
         - name: major_depression
           identifier: adult_population_covered_in_primary_data_on_the_prevalence_of_major_depression
           description: taux de couverture des données de dépression majeure sur la population adulte dans différentes régions du monde en 2008
           columns:
             - name: entity
               description: region
               tests:
                 - not_null
             - name: code
               description: region code
             - name: year
               description: year
               tests:
                 - not_null
             - name: major_depression
               description: taux de couverture de données
               tests:
                 - not_null
         - name: adult_population_covered
           identifier: adult_population_covered_in_primary_data_on_the_prevalence_of_mental_illnesses
           description: taux de couverture des données de pathologies mentales sur la population adulte dans différentes régions du monde en 2008 
           columns:
             - name: entity
               description: region
               tests:
                 - not_null
             - name: code
               description: region code
             - name: year
               description: year
               tests:
                 - not_null
             - name: major_depression
               description: major depression
               tests:
                 - not_null
             - name: bipolar_disorder
               description: bipolar disorder
               tests:
                 - not_null
             - name: eating_disorders
               description: major depression
               tests:
                 - not_null
             - name: dysthymia
               description: dysthymia
               tests:
                 - not_null
             - name: schizophrenia
               description: schizophrenia
               tests:
                 - not_null
             - name: anxiety_disorders
               description: anxiety disorders
               tests:
                 - not_null                               
         - name: anxiety_treatment_gap
           identifier: anxiety_disorders_treatment_gap
           description: taux de couverture des données de pathologies mentales sur la population adulte dans différentes régions du monde en 2008 
           columns:
             - name: entity
               description: country
               tests:
                 - not_null
             - name: code
               description: country code
             - name: year
               description: year
               tests:
                 - not_null
             - name: potentially_adequate_treatment_conditional
               description: percentage of potentially adequate treatments
               tests:
                 - not_null
             - name: other_treatments_conditional
               description: percentage of other treatments
               tests:
                 - not_null
             - name: untreated_conditional
               description: percentage of untreated population
               tests:
                 - not_null
         - name: depressive_symptoms
           identifier: depressive_symptoms_across_us_population
           description: récurrence de chaque symptôme de dépression aux Etats-Unis en 2014 
           columns:
             - name: entity
               description: symptom name
               tests:
                 - not_null
             - name: code
               description: country code
             - name: year
               description: year
               tests:
                 - not_null
             - name: nearly_every_day
               description: year
               tests:
                 - not_null
         - name: nb_of_countries_with_data_on_prevalence_of_mental_disorders
           identifier: number_of_countries_with_primary_data_on_prevalence_of_mental_illnesses_in_the_global_burden_of_disease_study
           description: nombre de pays ayant de la donnée sur les troubles mentaux en 2019
           columns:
             - name: entity
               description: mental disorder
               tests:
                 - not_null
             - name: code
               description: country code
             - name: year
               description: year
               tests:
                 - not_null
             - name: number_of_countries_with_primary_data_on_prevalence_of_mental_disorders
               description: nb de pays
               tests:
                 - not_null
         - name: france_hospitalisation
           identifier: france_hospitalisation #What is the exact name of the table in  BQ
           description: Données sur l'hospitalisation pour cause de santé mentale dans les départements français 
           columns:
             - name: departement
               description: code ISO départements français
             - name: densite_lit_2015
               description: taux de densité de lits en psychiatrie en 2015
             - name: densite_lit_2019
               description: taux de densité de lits en psychiatrie en 2019
             - name: densite_centre_2015
               description: taux de densité de centres psychothérapiques en 2015   
             - name: densite_centre_2019
               description: taux de densité de centres psychothérapiques en 2019
             - name: tx_hosp_tmf_2015
               description: taux d'hospitalisation pour troubles moyens fréquents en 2015
             - name: tx_hosp_tmf_2019
               description: taux d'hospitalisation pour troubles moyens fréquents en 2019
             - name: tx_hosp_tms_2015
               description: taux d'hospitalisation pour troubles moyens sévères en 2015
             - name: tx_hosp_tms_2019
               description: taux d'hospitalisation pour troubles moyens sévères en 2019
             - name: tx_recours_etablissement_ts_2015
               description: taux de recours à un établissement en cas de tentative de suicide en 2015
             - name: tx_recours_etablissement_ts_2019
               description: taux de recours à un établissement en cas de tentative de suicide en 2019
             - name: duree_moy_hosp_tmf_2015
               description: durée moyenne d'hospitalisation pour troubles moyens fréquents en 2015
             - name: duree_moy_hosp_tmf_2019
               description: durée moyenne d'hospitalisation pour troubles moyens fréquents en 2019
             - name: duree_moy_hosp_tms_2015
               description: durée moyenne d'hospitalisation pour troubles moyens sévères en 2015
             - name: duree_moy_hosp_tms_2019
               description: durée moyenne d'hospitalisation pour troubles moyens sévères en 2019
             - name: tx_rehosp_30j_tmf_2015
               description: taux de réhospitalisation à 30 jours pour troubles moyens fréquents en 2015
             - name: tx_rehosp_30j_tmf_2019
               description: taux de réhospitalisation à 30 jours pour troubles moyens fréquents en 2019
             - name: tx_rehosp_30j_tms_2015
               description: taux de réhospitalisation à 30 jours pour troubles moyens sévères en 2015
             - name: tx_rehosp_30j_tms_2019
               description: taux de réhospitalisation à 30 jours pour troubles moyens sévères en 2019
